-- ════════════════════════════════════════════════════════════════════════════
-- SDC INDIA — Seed Data  (run AFTER 01_schema.sql and 02_storage.sql)
--
-- Migrates the data currently hardcoded in src/data/*.ts into Postgres.
-- Idempotent: uses slug-based ON CONFLICT to avoid duplicates on re-run.
-- ════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────
-- EVENTS (15 — from src/data/events.ts)
-- ─────────────────────────────────────────────────────
insert into events (slug, title, description, event_date, event_time, location, category, mode, speakers, attendees, seats, duration, image_url, winners, is_published, registration_open, display_order) values
('vibe-code-2025',        'VIBE CODE Hackathon',           'A 12-hour AI-focused hackathon where students ideate, build, and refine AI-driven applications through hands-on collaboration and real-world problem solving. Held at Draper Startup House.',                                                  '2025-11-09', '9:00 AM',  'Draper Startup House, Hyderabad',  'Hackathon',  'OFFLINE', 'Industry Mentors & Judges',                                                  200, null, '1 Day',   '/assets/events/vibe-code-hackathon.jpg', ARRAY['Dhanvantari Team','HackstreetBoys','Ravens'],                       true, false, 10),
('ai-agents-workshop',    'AI Agents Workshop',            'Hands-on experience in AI and automation. Participants learned to build and deploy AI workflows using n8n, and explored tools like Cursor, Lovable, and Napkin AI.',                                                                    '2025-08-07', '10:00 AM', 'SNIST Campus, Hyderabad',          'Workshop',   'OFFLINE', 'Chandan Kumar Cheripally, Shubham Lal, Chandrashekhar M',                    120, null, '1 Day',   '/assets/events/ai-agents.jpg',           ARRAY[]::text[],                                                            true, false, 20),
('summer-backend-2025',   'Summer Backend Bootcamp',       'Practical bootcamp on server-side development covering client-server architecture, RESTful APIs, MongoDB/MySQL, Node.js and Express.js with live coding and mini-projects.',                                                              '2025-05-20', '10:00 AM', 'SNIST Campus, Hyderabad',          'Bootcamp',   'OFFLINE', 'SDC Core Team',                                                              80,  null, '2 Weeks', '/assets/events/backend-bootcamp.jpg',    ARRAY[]::text[],                                                            true, false, 30),
('ai-summit-2025',        'AI Summit 2025',                'Hands-on sessions on building LLMs, AI agents, and custom GPTs. Featured book launch of Azure OpenAI Essentials, VR experience, and panel discussions on AI''s impact on industries.',                                                       '2025-03-15', '9:00 AM',  'Swecha Open Source, Hyderabad',    'Conference', 'OFFLINE', 'Adithya Saladi, Dodagatta Nihar, Tech Boy Deepak',                           300, null, '1 Day',   '/assets/events/ai-summit.jpg',           ARRAY[]::text[],                                                            true, false, 40),
('ai-day-2025',           'AI Day 2025',                   'Focused on equipping students with AI knowledge and skills. Session by Om Ashish Mishra on How AI Works. First in a series of AI-focused events by SDC INDIA.',                                                                            '2025-02-16', '10:00 AM', 'Growth Hub, Hyderabad',            'Workshop',   'OFFLINE', 'Om Ashish Mishra, Tech Boy Deepak',                                          100, null, '1 Day',   '/assets/events/ai-day-2025.jpg',         ARRAY[]::text[],                                                            true, false, 50),
('hash-it-out-2',         'Hash-It-Out Season 2',          'State-level hackathon bringing together students from across Telangana to solve real-world problems. Focused on team building, networking, and technical innovation.',                                                                       '2024-11-20', '9:00 AM',  'SNIST Campus, Hyderabad',          'Hackathon',  'OFFLINE', 'Industry Mentors',                                                           400, null, '1 Day',   '/assets/events/hash-it-out-2.jpg',       ARRAY['Sticky Fingers','Team Spartans','Team Vrinchi'],                     true, false, 60),
('uxplosion-2',           'UXplosion 2.0',                 'Five-day intensive UI/UX bootcamp led by Madhu Pilli covering design thinking, wireframing, prototyping, Figma advanced techniques, and concluding with a live hackathon.',                                                                '2024-09-15', '7:00 PM',  'SNIST Campus, Hyderabad',          'Workshop',   'OFFLINE', 'Madhu Pilli',                                                                150, null, '6 Days',  '/assets/events/uxplosion-1.jpg',         ARRAY['Team MAC 1','Team VisionX','Team 2 Pixels Apart'],                   true, false, 70),
('uxplosion-1',           'UXplosion – Where Creativity Meets Functionality', 'Seven-day UI/UX bootcamp with Frederick Devarampati (Forbes 30U30 Asia). Covered Figma, prototyping, component creation, and concluded with India''s first UI/UX designing hackathon.',                              '2024-06-17', '7:00 PM',  'Online + SNIST Campus',            'Workshop',   'HYBRID',  'Frederick Devarampati – Founder, CEO Hotnot Fashion',                        180, null, '7 Days',  '/assets/events/uxplosion-1.jpg',         ARRAY['Team Design Squat','Team Anonymous','Team High Flyers'],             true, false, 80),
('beyond-tech-2024',      'Beyond Tech 2024 Hyderabad',    '5+ speakers across 5 technology topics with 9+ hours of keynotes and hands-on learning. 250+ participants at Microsoft Hyderabad Campus.',                                                                                              '2024-06-15', '9:00 AM',  'Microsoft Hyderabad Campus',       'Conference', 'OFFLINE', 'Harshith Sai Tunuguntla, Adithya Saladi, Saideep Reddy',                     250, null, '1 Day',   '/assets/events/beyond-tech-2024.png',    ARRAY[]::text[],                                                            true, false, 90),
('tech-vision-bangalore', 'Tech Vision – Bangalore',       'Hosted at Microsoft Bangalore with sessions on Prompt Engineering, UI/UX, Data Engineering, AI, Reverse Engineering, and Open AI from renowned industry speakers.',                                                                       '2024-03-20', '9:00 AM',  'Microsoft Bangalore',              'Conference', 'OFFLINE', 'Harshith Sai Tunuguntla, Anurag Srivastava, Lakshit Pant',                   150, null, '1 Day',   '/assets/events/techvision.jpg',          ARRAY[]::text[],                                                            true, false, 100),
('aleph-zero-blockchain', 'Aleph Zero Blockchain Workshop','Deep dive into Blockchain & Web3 with hands-on quests, NFT rewards, and networking. Covered Blockchain fundamentals, Web3, and the Aleph Zero ecosystem.',                                                                              '2024-02-15', '2:00 PM',  'SNIST Campus, Hyderabad',          'Workshop',   'OFFLINE', 'Rajashekar Makala, Siv Ram Shastri Jonnalagadda',                            100, null, '1 Day',   '/assets/events/blockchain.jpg',          ARRAY[]::text[],                                                            true, false, 110),
('ds-ai-workshop-2023',   'Data Science & AI Workshop',    'Collaboration with Microsoft Learn Student Ambassadors at Microsoft Office. 240+ students learned data science fundamentals, ML, and predictive modeling.',                                                                            '2023-11-10', '10:00 AM', 'Microsoft Office, Hyderabad',      'Workshop',   'OFFLINE', 'Bilal Aamer, Moinuddin Mohammed',                                            240, null, '1 Day',   '/assets/events/ds-workshop.jpg',         ARRAY[]::text[],                                                            true, false, 120),
('hash-it-out-1',         'Hash-It-Out Season 1',          'SDC''s inaugural state-level hackathon on October 6th. Brought together students to solve local problems using technology. Teams from CMRCET, SIET, and SNIST competed.',                                                                '2023-10-06', '9:00 AM',  'SNIST Campus, Hyderabad',          'Hackathon',  'OFFLINE', 'Industry Mentors',                                                           200, null, '1 Day',   '/assets/events/hackathon_event.png',     ARRAY['Tech Innovators (CMRCET)','The Originals (SIET)','Team Ashish (SNIST)'], true, false, 130),
('summer-tech-camp-2023', 'SDC Summer Tech Camp',          '30-day summer bootcamp for beginners covering HTML, CSS, JavaScript, and Bootstrap frontend development. Held on alternative days from May 16 to June 10, 2023.',                                                                       '2023-05-16', '10:00 AM', 'Online',                           'Bootcamp',   'ONLINE',  'SDC Core Team',                                                              100, null, '30 Days', '/assets/events/tech-bootcamp.jpg',       ARRAY[]::text[],                                                            true, false, 140),
('hack-for-hyderabad-1',  'HACK FOR HYDERABAD Edition 1',  'A National Level Hackathon that brings together developers nationwide to collaborate, innovate, and build impactful solutions addressing real-world challenges through technology.',                                                     null,         null,       'Hyderabad',                        'Hackathon',  'OFFLINE', 'TBD',                                                                        0,   300,  '12 Hours',  '/assets/events/hackwithhyd.jpg',         ARRAY[]::text[],                                                            true, false, 1)
on conflict (slug) do nothing;

-- ─────────────────────────────────────────────────────
-- TEAM MEMBERS
-- ─────────────────────────────────────────────────────
insert into team_members (slug, initials, name, role, bio, skills, impact, gradient, section, github_url, display_order) values
('chandrashekhar-m', 'CM', 'Chandrashekhar M',  'Founder',           'Founded SDC in 2022 at Sreenidhi Institute of Science and Technology (SNIST). A SNIST alumnus from the 2021–2024 batch, his vision was to create a space where students could grow technically through collaboration and hands-on learning — moving beyond classroom theory into real-world technology. Under his leadership, SDC has grown to 2500+ members with a national footprint as SDC INDIA.', ARRAY['Community Building','Vision','Mentorship','Leadership','Event Strategy'], 'Founded SDC · Grew it to 2500+ members', 'linear-gradient(135deg,#e84393,#f97316)', 'Founder', null, 1),
('pavan-kumar',      'PK', 'Pavan Kumar',        'Core Contributor',  'Active contributor to SDC INDIA''s open-source projects and community platforms. Works on the SDC website and developer tooling.',                                                                                                                                                                                                                                                                ARRAY['Web Development','TypeScript','React','Open Source'],                      'SDC INDIA website & tooling',           'linear-gradient(135deg,#22c55e,#06b6d4)', 'Core',    'https://github.com/goutipavankumar1249', 10),
('rithwik',          'RT', 'Rithwik',            'Core Contributor',  'Active contributor to SDC INDIA''s GitHub repositories. Part of the team driving open-source initiatives within the community.',                                                                                                                                                                                                                                                                       ARRAY['Development','Open Source','Collaboration'],                                'Open-source contributions',             'linear-gradient(135deg,#a855f7,#e84393)', 'Core',    'https://github.com/Rithwik29102006', 11),
('bhavitha',         'BH', 'Bhavitha',           'Core Contributor',  'Contributor to SDC INDIA''s projects, focused on building and maintaining community-driven open-source work.',                                                                                                                                                                                                                                                                                            ARRAY['Development','Open Source','Collaboration'],                                'Project contributions',                 'linear-gradient(135deg,#f97316,#a855f7)', 'Core',    'https://github.com/bhavitha-1306', 12),
('shashank-puram',   'SP', 'Shashank Puram',     'Core Contributor',  'Contributor to SDC INDIA''s open-source repositories and engineering initiatives.',                                                                                                                                                                                                                                                                                                                           ARRAY['Development','Open Source','Engineering'],                                  'Engineering contributions',             'linear-gradient(135deg,#06b6d4,#f59e0b)', 'Core',    'https://github.com/ShashankPuram', 13)
on conflict (slug) do nothing;

-- ─────────────────────────────────────────────────────
-- HIGHLIGHTS
-- ─────────────────────────────────────────────────────
insert into highlights (slug, team_name, initials, position, position_icon, event_name, event_date_label, event_image_url, description, gradient, stats, display_order) values
('dhanvantari',      'Dhanvantari Team',           'DT', '1st', '🏆', 'VIBE CODE Hackathon',     'November 2025', '/assets/events/vibe-code-hackathon.jpg', 'Crowned champions of VIBE CODE 2025 — a 12-hour AI-focused hackathon at Draper Startup House. Their winning entry showcased rapid ideation, technical depth, and a real-world problem solved through AI-driven engineering.',                              'linear-gradient(135deg,#e84393,#f97316)', '[{"value":"1st","label":"PLACE"},{"value":"12h","label":"BUILD TIME"},{"value":"200","label":"COMPETITORS"},{"value":"AI","label":"FOCUS"}]'::jsonb, 1),
('hackstreet',       'HackstreetBoys',             'HB', '2nd', '🥈', 'VIBE CODE Hackathon',     'November 2025', '/assets/events/vibe-code-hackathon.jpg', 'Strong runners-up at VIBE CODE Hackathon 2025. Shipped an AI-driven product in 12 hours alongside 200 fellow developers — demonstrating sharp engineering and team coordination under time pressure.',                                                       'linear-gradient(135deg,#a855f7,#e84393)', '[{"value":"2nd","label":"PLACE"},{"value":"12h","label":"BUILD TIME"},{"value":"200","label":"COMPETITORS"},{"value":"AI","label":"FOCUS"}]'::jsonb, 2),
('sticky',           'Sticky Fingers',             'SF', '1st', '🏆', 'Hash-It-Out Season 2',    'November 2024', '/assets/events/hash-it-out-2.jpg',       'Winners of Hash-It-Out Season 2 — SDC''s Telangana state-level hackathon with 400 students. Solved a real-world problem with elegant code, clean architecture, and standout teamwork.',                                                                       'linear-gradient(135deg,#22c55e,#06b6d4)', '[{"value":"1st","label":"PLACE"},{"value":"400","label":"COMPETITORS"},{"value":"STATE","label":"LEVEL"},{"value":"1","label":"DAY"}]'::jsonb, 3),
('mac1',             'Team MAC 1',                 'M1', '1st', '🏆', 'UXplosion 2.0',           'September 2024','/assets/events/uxplosion-1.jpg',         'Winners of UXplosion 2.0 — the five-day UI/UX bootcamp led by Madhu Pilli, culminating in a live design hackathon. Beautiful interface work, sharp execution, and a clear user-centered story.',                                                              'linear-gradient(135deg,#f97316,#a855f7)', '[{"value":"1st","label":"PLACE"},{"value":"150","label":"COMPETITORS"},{"value":"6","label":"DAYS"},{"value":"Figma","label":"TOOL"}]'::jsonb, 4),
('designsquat',      'Team Design Squat',          'DS', '1st', '🏆', 'UXplosion Season 1',      'June 2024',     '/assets/events/uxplosion-2.jpg',         'Winners of UXplosion Season 1 — India''s first UI/UX designing hackathon, mentored by Forbes 30U30 Asia honoree Frederick Devarampati. Strong concept, polished execution, deserved win.',                                                                    'linear-gradient(135deg,#06b6d4,#a855f7)', '[{"value":"1st","label":"PLACE"},{"value":"180","label":"COMPETITORS"},{"value":"7","label":"DAYS"},{"value":"1st","label":"IN INDIA"}]'::jsonb, 5),
('techinnovators',   'Tech Innovators (CMRCET)',   'TI', '1st', '🏆', 'Hash-It-Out Season 1',    'October 2023',  '/assets/events/hackathon_event.png',     'Winners of Hash-It-Out Season 1 — SDC''s inaugural hackathon. The CMRCET team beat squads from SIET and SNIST with a sharp local-problem solution that earned them the top prize.',                                                                            'linear-gradient(135deg,#f59e0b,#e84393)', '[{"value":"1st","label":"PLACE"},{"value":"200","label":"COMPETITORS"},{"value":"3","label":"COLLEGES"},{"value":"1st","label":"EDITION"}]'::jsonb, 6)
on conflict (slug) do nothing;

-- ─────────────────────────────────────────────────────
-- BLOG POSTS
-- ─────────────────────────────────────────────────────
insert into blog_posts (slug, title, category, publish_date, read_time, cover_image_url, excerpt, content_blocks, is_published, display_order) values
('story-behind-sdc',          'The Story Behind SDC: A Community Built for Builders', 'article',   '2026-03-01', '5 min read', '/assets/blog/sdc-india-logo.jpeg', 'The Student Developers Community (SDC) was established in 2022 at Sreenidhi Institute of Science and Technology. The goal was simple: create an environment where students can learn by building.', '[{"paragraphs":["The Student Developers Community (SDC) was established in 2022 at Sreenidhi Institute of Science and Technology (SNIST) with a clear mission: build a student-first technical ecosystem.","From day one, SDC focused on practical exposure through workshops, bootcamps, hackathons, and peer collaboration."],"quote":"Learning by doing - that''s the SDC way."},{"title":"Where We Are Today","paragraphs":["Today, SDC has grown into a strong technical community with over 2500 members and a growing national footprint under SDC INDIA."]},{"title":"Our Core Values","bullets":["Open and inclusive learning environment","Real-world, hands-on exposure","Peer collaboration over competition","Industry-aligned skill building"]}]'::jsonb, true, 1),
('founder-and-vision',        'Founder and Vision Behind SDC',                        'community', '2026-02-01', '4 min read', '/assets/blog/community-1.jpeg',     'Founded by Chandrashekhar M, SDC was built to close the gap between classroom learning and industry expectations.',                                                                                  '[{"paragraphs":["SDC was founded by Mr. Chandrashekhar M, a SNIST alumnus from the 2021-2024 batch.","His vision centered on creating an inclusive environment where students can gain confidence through collaboration and practical experience."]},{"title":"Growth Under Leadership","bullets":["Hosted impactful student-focused events","Built collaborations with industry professionals","Formed partnerships with national communities","Expanded to 2500+ members"],"quote":"The founding values continue to shape SDC''s culture and growth path."}]'::jsonb, true, 2),
('major-events-and-hackathons','Major Events and Hackathons That Defined SDC',         'event',     '2025-12-01', '6 min read', '/assets/blog/event.jpeg',          'SDC events evolved into practical career launchpads through workshops, hackathons, and national partnerships.',                                                                                       '[{"title":"Key Initiatives","bullets":["SDC Summer Tech Camp","UI/UX Workshop","Python for Data Science","Backend Development Bootcamp","AI Workshop at Microsoft","Beyond Tech at Microsoft Hyderabad","AI Day at Growth Hub","AI Summit 2025","Aleph Zero Blockchain Workshop","Smart India Hackathon Guidance Sessions"]},{"title":"Flagship Hackathons","paragraphs":["Hash It Out and UX-Plosion became defining experiences where students built deployable solutions with mentorship from industry experts."]},{"title":"Community Partnerships","paragraphs":["SDC partnered with events like PyCon India, Hack This Fall, Hack 4 Hire, Social Media Summit, Techknowthon, and GDSC WOW."]}]'::jsonb, true, 3),
('campus-to-sdc-india',       'From Campus Club to SDC INDIA',                        'growth',    '2025-10-01', '3 min read', '/assets/blog/snist.jpeg',           'SDC expanded from a campus initiative into a nationwide student developer movement with new chapters and broader impact.',                                                                            '[{"paragraphs":["SDC scaled from a local campus initiative into SDC INDIA, expanding across institutions and regions.","The launch of chapters like SDC SPEC strengthened the innovation ecosystem and reach."],"quote":"The long-term vision is a connected nationwide student developer network."}]'::jsonb, true, 4),
('digital-presence',          'SDC''s Digital Presence: Where the Community Lives Online','digital','2025-08-01', '3 min read', '/assets/blog/community-3.jpeg',     'From the website to GitHub, LinkedIn, and Instagram, SDC''s digital channels keep the community connected.',                                                                                          '[{"paragraphs":["The SDC India website serves as the central hub for mission updates, events, and community initiatives."]},{"title":"Primary Platforms","bullets":["LinkedIn for professional updates and opportunities","Instagram for highlights and community storytelling","GitHub for open-source collaboration and project sharing"]}]'::jsonb, true, 5),
('why-sdc-member',            'Why Being an SDC Member Changes Everything',           'article',   '2025-06-01', '5 min read', '/assets/blog/community-2.jpeg',     'Membership unlocks mentorship, practical exposure, events, and a high-trust community that accelerates growth.',                                                                                       '[{"title":"Experiential Learning and Mentorship","paragraphs":["Through events like HASH IT OUT and UX-Plosion, students solve real-world problems with mentorship and structured feedback."]},{"title":"Professional Networking","paragraphs":["National partnerships and industry-hosted events help members connect with recruiters, founders, and practitioners."]},{"title":"Holistic Growth","bullets":["Teamwork and leadership","Communication and presentation","Open-source contribution","Public project showcases"]}]'::jsonb, true, 6),
('beyond-tech-microsoft',     'Beyond Tech at Microsoft Hyderabad: A Recap',          'event',     '2025-04-01', '4 min read', '/assets/blog/community-3.jpeg',     'Beyond Tech brought students, professionals, and founders together to discuss practical career pathways and AI innovation.',                                                                          '[{"paragraphs":["SDC co-hosted Beyond Tech and AI workshop sessions at Microsoft Hyderabad to connect students directly with experienced professionals."]},{"title":"Key Takeaways","bullets":["Networking with recruiters and startup founders","Live Q and A with industry experts","AI workshops around product use cases","Exposure to enterprise innovation workflows"]}]'::jsonb, true, 7)
on conflict (slug) do nothing;

-- ─────────────────────────────────────────────────────
-- PARTNERS
-- ─────────────────────────────────────────────────────
insert into partners (slug, name, logo_url, display_order) values
('microsoft-learn',  'Microsoft Learn',                          '/assets/partners/microsoft-learn.svg',  1),
('iete',             'IETE',                                     '/assets/partners/iete.svg',             2),
('code-sprint',      'Code Sprint',                              '/assets/partners/code-sprint.svg',      3),
('hack-this-fall',   'Hack This Fall',                           '/assets/partners/hack-this-fall.svg',   4),
('gdsc-wow',         'Google Developer Student Clubs WOW',       '/assets/partners/gdsc-wow.svg',         5),
('edventure',        'EdVenture Park',                           '/assets/partners/edventure.svg',        6),
('pycon-india',      'PyCon India Hyderabad 2023',               '/assets/partners/pycon.svg',            7),
('st',               'ST',                                       '/assets/partners/st.svg',               8),
('talentmapp',       'Talentmapp',                               '/assets/partners/talentmapp.svg',       9),
('ecell',            'E-Cell',                                   '/assets/partners/ecell.svg',           10)
on conflict (slug) do nothing;

-- ─────────────────────────────────────────────────────
-- GALLERY IMAGES
-- ─────────────────────────────────────────────────────
insert into gallery_images (image_url, alt_text, span_classes, display_order) values
('/assets/blog/event.jpeg',         'SDC Event',     'col-span-2 aspect-[2/1]', 1),
('/assets/blog/snist.jpeg',         'SNIST Campus',  'aspect-square',           2),
('/assets/blog/community-1.jpeg',   'Community',     'aspect-square',           3),
('/assets/blog/community-2.jpeg',   'Members',       'aspect-square',           4),
('/assets/blog/community-3.jpeg',   'Team',          'aspect-square',           5);

-- ════════════════════════════════════════════════════════════════════════════
-- Quick verification — run these queries after the seed to confirm counts.
-- ════════════════════════════════════════════════════════════════════════════
--   select count(*) as events       from events;        -- 15
--   select count(*) as team         from team_members;  --  5
--   select count(*) as blog         from blog_posts;    --  7
--   select count(*) as highlights   from highlights;    --  6
--   select count(*) as partners     from partners;      -- 10
--   select count(*) as gallery      from gallery_images;--  5
--   select count(*) as admins       from admin_emails;  --  1
